[build]
  command = ""
  publish = "dist"
  ignore_html_forms = true

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/stylesheets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/javascripts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
